from pydantic import BaseModel, Field
from typing import List

class RAGResponse(BaseModel):
    answer: str = Field(description="The final answer to the user query based on the retrieved documents.")
    sources: List[str] = Field(description="List of cited source materials or documents.")

class QueryRequest(BaseModel):
    query: str = Field(..., min_length=1, description="The query to send to the RAG pipeline.")
    thread_id: str = Field("default_thread", description="The thread identifier to persist chat history.")

class QueryResponse(BaseModel):
    answer: str = Field(..., description="The answer generated by the cRAG pipeline.")
    sources: List[str] = Field(..., description="The source citations used for the answer.")

class ChatLogItem(BaseModel):
    timestamp: str
    user_query: str
    ai_response: str

class ThreadHistoryResponse(BaseModel):
    thread_id: str
    history: List[ChatLogItem]

class ErrorResponse(BaseModel):
    detail: str
    error_code: str
