from pydantic import BaseModel, Field
from typing import List

class RAGResponse(BaseModel):
    answer: str = Field(description="The final answer to the user query based on the retrieved documents.")
    sources: List[str] = Field(description="List of cited source materials or documents.")

class QueryRequest(BaseModel):
    query: str = Field(..., min_length=1, max_length=2000, description="The query to send to the RAG pipeline.")
    thread_id: str = Field(..., description="The unique thread identifier generated by the backend.")
    user_id: str = Field(..., description="The unique user identifier.")

class QueryResponse(BaseModel):
    answer: str = Field(..., description="The answer generated by the cRAG pipeline.")
    sources: List[str] = Field(..., description="The source citations used for the answer.")

class ChatLogItem(BaseModel):
    timestamp: str
    user_query: str
    ai_response: str

class ThreadHistoryResponse(BaseModel):
    thread_id: str
    user_id: str
    history: List[ChatLogItem]

class CreateThreadResponse(BaseModel):
    thread_id: str = Field(..., description="The unique thread ID generated by the backend.")
    user_id: str = Field(..., description="The owner user identifier.")
    title: str = Field(..., description="The title of the chat thread.")
    created_at: str = Field(..., description="The creation timestamp.")

class ThreadItem(BaseModel):
    thread_id: str
    user_id: str
    title: str
    created_at: str

class ThreadListResponse(BaseModel):
    threads: List[ThreadItem]
